# site settings
title: Darkato
subtitle: 42
email: me+42@wu-yulin.com
description: A curious full stack engineer<br />❤️ unconventionally laziness.
baseurl: "/wu-yulin.com" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United Kingdom
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/darkato42
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/yulin-wu/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
